### ISSUE TITLE
Related to the librosa.display.specshow function：TypeError: Dimensions of C (129, 48) are incompatible with X (1730) and/or Y (129); see help(pcolormesh)

### ISSUE THREAD

**Issue by Mxnet123** [jin-woo-lee/hrtf-interpolation#1]
Hello，I found a problem with the use of the librosa.display.specshow function in the interp-hutubs.py file, EST_np[s].T.shape=(129, 1730),x.shape=x (1730,), which seems wrong, x.shape should be changed to (1731,),. Similarly y.shape should be changed to (130,)

**Comment by jin-woo-lee** [comment]
Hi, thanks for your comment.
I've double-checked `interp-hutubs.py` but found it running well.
The spectrogram should have the same size as `x` and `y` (i.e., `EST_np[s].T.shape == [129,48]`).
So the number of grids in that code should be [`G == 48`](https://github.com/jin-woo-lee/hrtf-interpolation/blob/main/interp-hutubs.py#L143).
Since you have [`num_grid == 1730`](https://github.com/jin-woo-lee/hrtf-interpolation/blob/main/interp-hutubs.py#L74) number of grids, I think the error might because of your modification from the original code perhaps?

**Comment by jin-woo-lee** [comment]
I'll close this; let me know if the issue persists.
